import { ReactNode } from "react";
import { Header } from "@frontend/components/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <div className="w-full h-[100vh] flex justify-center items-center">
      <div className="w-[500px] p-[30px] rounded-xl border border-black/10">
        {children}
      </div>
    </div>
  );
}
